// <auto-generated />
namespace Arvato.IQ.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TitleIX : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TitleIX));
        
        string IMigrationMetadata.Id
        {
            get { return "201610240024490_TitleIX"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
